# Optimasi Vehicle Routing Problem <br> Alur Pembuangan Sampah Kota Surabaya
<b> Kelompok 08 </b> <br>
Nama Anggota :
1. Nida Aulia Amartika			(5026221095)
2. Isaura Qinthara Heriswan		(5026221146)
3. Devy Relliani Saffiyah		(5026221189)

# Main

In [1]:
%pip install scikit-learn
%pip install folium
%pip install pandas

Requirement already satisfied: scikit-learn in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.6.0 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: folium in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (0.19.7)
Requirement already satisfied: branca>=0.6.0 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from folium) (2.2.6)
Requirement already satisfied: requests in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from folium) (2025.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from requests->folium) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from requests->folium) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from requests->folium) (2025.4.26)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\devy relliani\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\devy relliani\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\devy relliani\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import random
from sklearn.cluster import KMeans
import folium
import math

In [3]:
df = pd.read_csv('new_data.csv')
df

,No,LPS/Depo,Alamat,Latitude,Longitude,Kapasitas_Sampah(m^3)
0,1,Demak (Kali Butuh),Jalan Demak,-7.253606,112.720422,6
1,2,Pringadi,Jalan Pringadi,-7.252544,112.733072,4
2,3,Penghela,Jalan Penghela,-7.248233,112.733186,3
3,4,Sulung Kali,Jalan Sulung Kali,-7.244014,112.742173,3
4,5,Dupak,Jalan Babatan Dupak,-7.244836,112.727439,2
5,6,Simolawang,Jalan Simolawang,-7.237522,112.753542,1
6,7,Pasar Kapasan,Jalan Simolawang Baru I,-7.239633,112.750247,5
7,8,Tambak Rejo,Jalan Kenjeran (depan Makam Rangkah),-7.243069,112.760314,6
8,9,Simpang Dukuh,Jalan Simpang Dukuh,-7.260503,112.742111,4
9,10,Pasar Genteng,Jalan Genteng Besar,-7.258242,112.740377,4
10,11,Kayun,Jalan Kayun,-7.269259,112.747528,5
11,12,Legundi Anggrek,Jalan Anggrek,-7.262483,112.752017,5
12,13,Pecindilan,Jalan Raya Pecindilan,-7.244094,112.747411,3
13,14,Makam Peneleh,Jalan Makam Peneleh,-7.252331,112.741364,3
14,15,Kedondong,Jalan Kedondong,-7.271773,112.738242,2
15,16,Kedung Anyar,Jalan Kedung Anyar,-7.254253,112.731048,1
16,17,Pasar Kembang,Jalan Wonorejo III Pasar,-7.269049,112.729097,1
17,18,Pandegiling,Jalan Pandegiling,-7.276231,112.735806,2
18,19,Dinoyo,Jalan Dinoyo,-7.278275,112.743403,3
19,20,Rumah Sakit Darmo / Ketampon,Jalan Taman Ketampon,-7.287677,112.736963,2
20,21,Keputran Selatan,Jalan Keputran Selatan,-7.274575,112.743370,1
21,22,3R Jambangan,Jalan Jambangan Kebon Agung,-7.313541,112.732069,3
22,23,Gayungsari,Jalan Gayungsari IV,-7.324832,112.749814,1
23,24,Nyamplungan,Jalan KH Mas Mansyur,-7.221696,112.750527,3
24,25,Kertopaten,Jalan Kertopaten,-7.230313,112.741019,4
25,26,Jagir,Jalan Bendul Merisi,-7.299018,112.753697,2
26,27,Prada Kali Kendal,Jalan Kali Kendal,-7.275311,112.695040,5
27,28,Wonokusumo Kidul,Jalan Wonokusumo Jaya,-7.225113,112.752340,2
28,29,Gubeng,Jalan Gubeng Kertajaya,-7.277812,112.761476,1
29,30,Sawahan,Jalan Sawahan Raya,-7.262594,112.728107,4
30,31,Kendung,Jalan Kendung,-7.247601,112.635484,3
31,32,Gayung Pring,Jalan Gayung,-7.337900,112.728200,2
32,33,Panghela,Jalan Panghela,-7.247908,112.733304,1
33,34,Giyu,Jalan Rungkut Industri,-7.331003,112.771393,3
34,35,Alas Malang,Jalan Alas Malang,-7.262228,112.643165,4
35,36,Babat Jerawat,Jalan DK Jerawat,-7.246167,112.629661,1
36,37,Srikana,Jalan Srikana,-7.273996,112.758097,2
37,38,Keputih,Jalan Raya Marina Asri,-7.294823,112.807148,3
38,39,Tambak Deres,Jalan Kyai Tambak Deres,-7.230860,112.785501,5
39,40,Pacar Keling,Jalan Tambang Boyo,-7.260621,112.758661,2
40,41,Kaiser,Jalan Makam,-7.276720,112.713377,1
41,42,Medokan Ayu,Jalan Medokan Asri Tengah,-7.326099,112.795516,1
42,43,Semolowaru Bahari,Jalan Semolowaru,-7.302239,112.788335,1
43,44,Gebang Putih,Jalan Gebang Putih,-7.284392,112.785407,3
44,45,Pesapen,Jalan Karang Ploso,-7.326542,112.674600,2

In [4]:
pool = (-7.26053139, 112.692194)   # Pool Tanjungsari
tpa  = (-7.23739100, 112.60943600) # TPA Benowo

In [5]:
m1 = folium.Map(location=pool, zoom_start=12)
folium.Marker(location=pool, popup='Pool Tanjungsari', icon=folium.Icon(color='red')).add_to(m1)
folium.Marker(location=tpa, popup='TPA Benowo', icon=folium.Icon(color='green')).add_to(m1)
for _, row in df.iterrows():
    folium.Marker(location=(row['Latitude'], row['Longitude']), popup=row['LPS/Depo']).add_to(m1)
m1  # Preview map before VRP

In [6]:
n_vehicles = 11
coords = df[['Latitude','Longitude']].values
kmeans = KMeans(n_clusters=n_vehicles, random_state=42).fit(coords)
df['cluster'] = kmeans.labels_

In [7]:
colors = ['blue', 'purple', 'orange', 'yellow', 'lightred', 'darkblue', 'darkgreen', 'cadetblue', 'darkpurple', 'pink', 'lightblue']

# Create a new map centered at the pool
m_cluster = folium.Map(location=pool, zoom_start=12)

# Add depot and TPA markers
folium.Marker(location=pool, popup='Pool Tanjungsari', icon=folium.Icon(color='red')).add_to(m_cluster)
folium.Marker(location=tpa, popup='TPA Benowo', icon=folium.Icon(color='green')).add_to(m_cluster)

# Add markers for each point, colored by cluster
for _, row in df.iterrows():
    folium.Marker(location=(row['Latitude'], row['Longitude']),
                  popup=f"{row['LPS/Depo']} (Cluster {row['cluster']})",
                  icon=folium.Icon(color=colors[row['cluster'] % len(colors)])).add_to(m_cluster)

# Display the map
m_cluster

C:\Users\Devy Relliani\AppData\Local\Temp\ipykernel_25572\1510036970.py:14: UserWarning: color argument of Icon should be one of: {'black', 'lightred', 'orange', 'white', 'red', 'blue', 'darkblue', 'lightgray', 'darkgreen', 'darkpurple', 'cadetblue', 'beige', 'lightgreen', 'lightblue', 'pink', 'darkred', 'gray', 'purple', 'green'}.
  icon=folium.Icon(color=colors[row['cluster'] % len(colors)])).add_to(m_cluster)

In [8]:
def haversine(a, b):
    R = 6371e3
    φ1, φ2 = math.radians(a[0]), math.radians(b[0])
    Δφ = math.radians(b[0] - a[0])
    Δλ = math.radians(b[1] - a[1])
    x = math.sin(Δφ/2)**2 + math.cos(φ1)*math.cos(φ2)*math.sin(Δλ/2)**2
    return R * 2 * math.asin(math.sqrt(x))

In [9]:
def route_distance(route):
    dist = 0
    prev = pool
    for pt in route:
        dist += haversine(prev, pt)
        prev = pt
    dist += haversine(prev, tpa) + haversine(tpa, pool)
    return dist

In [10]:
def order_crossover(p1, p2):
    size = len(p1)
    a, b = sorted(random.sample(range(size), 2))
    c1 = [None]*size
    c2 = [None]*size
    c1[a:b], c2[a:b] = p1[a:b], p2[a:b]
    def fill(child, parent):
        pos = b
        for gene in parent[b:] + parent[:b]:
            if gene not in child:
                if pos >= size: pos = 0
                child[pos] = gene
                pos += 1
    fill(c1, p2)
    fill(c2, p1)
    return c1, c2

In [11]:
def mutate(ind):
    if len(ind) > 1:
        i, j = random.sample(range(len(ind)), 2)
        ind[i], ind[j] = ind[j], ind[i]

In [12]:
def ga_cluster(points, pop_size=150, gens=800, elite_size=1):
    n = len(points)
    if n < 2:
        return points

    # initialize population
    population = [random.sample(range(n), n) for _ in range(pop_size)]

    for _ in range(gens):
        # compute fitness for roulette selection
        fitness = [1/(route_distance([points[i] for i in ind]) + 1) for ind in population]
        total = sum(fitness)
        probs = [f/total for f in fitness]

        # select elites (best individuals) to carry forward
        sorted_pop = sorted(
            population,
            key=lambda ind: route_distance([points[i] for i in ind])
        )
        new_pop = [sorted_pop[i].copy() for i in range(elite_size)]

        # fill the rest of new_pop by crossover + mutation
        while len(new_pop) < pop_size:
            # select two parents
            p1, p2 = random.choices(population, probs, k=2)
            # crossover
            if random.random() < 0.8:
                c1, c2 = order_crossover(p1, p2)
            else:
                c1, c2 = p1[:], p2[:]
            # mutate
            if random.random() < 0.2:
                mutate(c1)
            if random.random() < 0.2:
                mutate(c2)

            new_pop.append(c1)
            if len(new_pop) < pop_size:
                new_pop.append(c2)

        population = new_pop

    # return the best route as actual coordinates
    best = min(
        population,
        key=lambda ind: route_distance([points[i] for i in ind])
    )
    return [points[i] for i in best]

In [13]:
m2 = folium.Map(location=pool, zoom_start=12)
folium.Marker(location=pool, popup='Pool Tanjungsari', icon=folium.Icon(color='red')).add_to(m2)
folium.Marker(location=tpa, popup='TPA Benowo', icon=folium.Icon(color='green')).add_to(m2)

coord_to_name = {
    (row['Latitude'], row['Longitude']): row['LPS/Depo']
    for _, row in df.iterrows()
}
coord_to_name[pool] = "Pool Tanjungsari"
coord_to_name[tpa]  = "TPA Benowo"

overall_distance = 0

for vid in range(n_vehicles):
    # get the raw coordinates in this cluster
    cluster_pts = coords[kmeans.labels_ == vid]
    if len(cluster_pts) == 0:
        continue

    # GA wants a Python list of tuple‐points
    pts_list = [tuple(pt) for pt in cluster_pts]

    # find best ordering of stops
    best_route = ga_cluster(pts_list)

    # build the full trip for plotting
    full_route = [pool] + best_route + [tpa, pool]

    # 1) draw it on the map
    folium.PolyLine(
        locations=full_route,
        color=colors[vid % len(colors)],
        weight=2.5, opacity=0.8,
        popup=f'Vehicle {vid+1}'
    ).add_to(m2)

    vehicle_distance = route_distance(best_route)
    total_dist_km = vehicle_distance / 1000
    
    # Add to total distance
    overall_distance += vehicle_distance

    # 3) map coords back to names
    path_names = [coord_to_name[c] for c in full_route]
    print(f"Vehicle {vid+1}: " + " → ".join(path_names))
    print(f"  Total distance: {total_dist_km:.2f} km\n")

# Print total combined distance
print(f"TOTAL DISTANCE ALL VEHICLES [GA]: {overall_distance / 1000:.2f} km")

# finally show the map
m2

Vehicle 1: Pool Tanjungsari → Pasar Kembang → Pandegiling → Kedondong → Keputran Selatan → Dinoyo → Rumah Sakit Darmo / Ketampon → TPA Benowo → Pool Tanjungsari
  Total distance: 32.77 km

Vehicle 2: Pool Tanjungsari → Giyu → Gayungsari → TPA Benowo → Pool Tanjungsari
  Total distance: 41.98 km

Vehicle 3: Pool Tanjungsari → Alas Malang → Kendung → Babat Jerawat → TPA Benowo → Pool Tanjungsari
  Total distance: 19.83 km

Vehicle 4: Pool Tanjungsari → Kayun → Srikana → Gubeng → Pacar Keling → Legundi Anggrek → TPA Benowo → Pool Tanjungsari
  Total distance: 36.18 km

Vehicle 5: Pool Tanjungsari → Jagir → 3R Jambangan → Gayung Pring → TPA Benowo → Pool Tanjungsari
  Total distance: 40.35 km

Vehicle 6: Pool Tanjungsari → Gebang Putih → Keputih → Medokan Ayu → Semolowaru Bahari → TPA Benowo → Pool Tanjungsari
  Total distance: 50.25 km

Vehicle 7: Pool Tanjungsari → Sulung Kali → Pecindilan → Pasar Kapasan → Tambak Rejo → Simolawang → Wonokusumo Kidul → Nyamplungan → Kertopaten → TPA Benowo → Pool Tanjungsari
  Total distance: 36.38 km

Vehicle 8: Pool Tanjungsari → Tambak Deres → TPA Benowo → Pool Tanjungsari
  Total distance: 39.73 km

Vehicle 9: Pool Tanjungsari → Sawahan → Kedung Anyar → Pringadi → Pasar Genteng → Simpang Dukuh → Makam Peneleh → Penghela → Panghela → Dupak → Demak (Kali Butuh) → TPA Benowo → Pool Tanjungsari
  Total distance: 32.38 km

Vehicle 10: Pool Tanjungsari → Pesapen → TPA Benowo → Pool Tanjungsari
  Total distance: 29.32 km

Vehicle 11: Pool Tanjungsari → Kaiser → Prada Kali Kendal → TPA Benowo → Pool Tanjungsari
  Total distance: 24.80 km

TOTAL DISTANCE ALL VEHICLES [GA]: 383.97 km

# VRP WITH ANT COLONY OPTIMIZATION

In [14]:
# Load kapasitas truk
df_truk = pd.read_csv('kapasitas-truk.csv', sep = ';')
df_truk

   No Jenis Kendaraan  Volume (m^3)
0   1      Truk Kecil             7
1   2    Truk 3.5 Ton            12
2   3  Arm Roll Truck            18

In [15]:
# Fungsi Ant Colony Optimization sederhana
def ant_colony_tsp(points, n_ants=70, n_iterations=300, alpha=1, beta=2, evaporation=0.4):
    n = len(points)
    dist_matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if i != j:
                dist_matrix[i][j] = haversine(points[i], points[j])
            else:
                dist_matrix[i][j] = 1e-6  # avoid divide by zero

    pheromone = np.ones((n, n))
    best_distance = float('inf')
    best_path = []

    for _ in range(n_iterations):
        all_paths = []
        all_lengths = []

        for _ in range(n_ants):
            unvisited = list(range(n))
            start = random.choice(unvisited)
            path = [start]
            unvisited.remove(start)

            while unvisited:
                curr = path[-1]
                probs = []
                for j in unvisited:
                    tau = pheromone[curr][j] ** alpha
                    eta = (1 / dist_matrix[curr][j]) ** beta
                    probs.append(tau * eta)
                probs = np.array(probs)
                probs /= probs.sum()
                next_node = np.random.choice(unvisited, p=probs)
                path.append(next_node)
                unvisited.remove(next_node)

            length = sum(dist_matrix[path[i]][path[i + 1]] for i in range(n - 1))
            length += haversine(pool, points[path[0]])  # pool to start
            length += haversine(points[path[-1]], tpa)  # end to TPA
            length += haversine(tpa, pool)             # TPA to pool

            all_paths.append(path)
            all_lengths.append(length)

        shortest_idx = np.argmin(all_lengths)
        if all_lengths[shortest_idx] < best_distance:
            best_distance = all_lengths[shortest_idx]
            best_path = all_paths[shortest_idx]

        # Update pheromone
        pheromone *= (1 - evaporation)
        for path, length in zip(all_paths, all_lengths):
            for i in range(n - 1):
                pheromone[path[i]][path[i + 1]] += 1 / length

    return [points[i] for i in best_path], best_distance

In [16]:
# Map baru ACO
m3 = folium.Map(location=pool, zoom_start=12)
total_distance_aco = 0
# Add depot and TPA markers
folium.Marker(location=pool, popup='Pool Tanjungsari', icon=folium.Icon(color='red')).add_to(m3)
folium.Marker(location=tpa, popup='TPA Benowo', icon=folium.Icon(color='green')).add_to(m3)

# Map koordinat ke kapasitas
coord_to_capacity = {
    (row['Latitude'], row['Longitude']): row['Kapasitas_Sampah(m^3)']
    for _, row in df.iterrows()
}

for vid in range(n_vehicles):
    cluster_pts = coords[kmeans.labels_ == vid]
    if len(cluster_pts) == 0:
        continue

    pts_list = [tuple(pt) for pt in cluster_pts]
    capacities = [coord_to_capacity[pt] for pt in pts_list]
    total_volume = sum(capacities)

    # Pilih truk terkecil yang muat
    truk_terpilih = None
    for _, row in df_truk.iterrows():
        if total_volume <= row['Volume (m^3)']:
            truk_terpilih = row
            break
    if truk_terpilih is None:
        truk_terpilih = df_truk.iloc[-1]  # Gunakan terbesar jika semuanya tidak cukup

    # ACO untuk rute terbaik
    best_path, best_dist = ant_colony_tsp(pts_list)
    total_distance_aco += best_dist

    # Bangun rute lengkap
    full_route = [pool] + best_path + [tpa, pool]
    color = colors[vid % len(colors)]
    folium.PolyLine(locations=full_route, color=color, weight=2.5,
                    opacity=0.8, popup=f'Vehicle {vid+1}').add_to(m3)

    path_names = [coord_to_name.get(c, 'Unknown') for c in full_route]


    print(f"[ACO] Vehicle {vid+1}: " + " → ".join(path_names))
    print(f"  Total distance: {best_dist/1000:.2f} km")
    print(f"  Total volume sampah: {total_volume:.1f} m^3")
    print(f"  Jenis truk yang digunakan: {truk_terpilih['Jenis Kendaraan']} (kapasitas {truk_terpilih['Volume (m^3)']} m^3)\n")

print(f"TOTAL DISTANCE ALL VEHICLES [ACO]: {total_distance_aco / 1000:.2f} km")
# Tampilkan map
m3

[ACO] Vehicle 1: Pool Tanjungsari → Pasar Kembang → Pandegiling → Kedondong → Keputran Selatan → Dinoyo → Rumah Sakit Darmo / Ketampon → TPA Benowo → Pool Tanjungsari
  Total distance: 32.77 km
  Total volume sampah: 11.0 m^3
  Jenis truk yang digunakan: Truk 3.5 Ton (kapasitas 12 m^3)

[ACO] Vehicle 2: Pool Tanjungsari → Giyu → Gayungsari → TPA Benowo → Pool Tanjungsari
  Total distance: 41.98 km
  Total volume sampah: 4.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)

[ACO] Vehicle 3: Pool Tanjungsari → Alas Malang → Kendung → Babat Jerawat → TPA Benowo → Pool Tanjungsari
  Total distance: 19.83 km
  Total volume sampah: 8.0 m^3
  Jenis truk yang digunakan: Truk 3.5 Ton (kapasitas 12 m^3)

[ACO] Vehicle 4: Pool Tanjungsari → Kayun → Srikana → Gubeng → Pacar Keling → Legundi Anggrek → TPA Benowo → Pool Tanjungsari
  Total distance: 36.18 km
  Total volume sampah: 15.0 m^3
  Jenis truk yang digunakan: Arm Roll Truck (kapasitas 18 m^3)

[ACO] Vehicle 5: Pool Tanjungsari → Jagir → 3R Jambangan → Gayung Pring → TPA Benowo → Pool Tanjungsari
  Total distance: 40.35 km
  Total volume sampah: 7.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)

[ACO] Vehicle 6: Pool Tanjungsari → Gebang Putih → Keputih → Medokan Ayu → Semolowaru Bahari → TPA Benowo → Pool Tanjungsari
  Total distance: 50.25 km
  Total volume sampah: 8.0 m^3
  Jenis truk yang digunakan: Truk 3.5 Ton (kapasitas 12 m^3)

[ACO] Vehicle 7: Pool Tanjungsari → Sulung Kali → Pecindilan → Pasar Kapasan → Tambak Rejo → Simolawang → Wonokusumo Kidul → Nyamplungan → Kertopaten → TPA Benowo → Pool Tanjungsari
  Total distance: 36.38 km
  Total volume sampah: 27.0 m^3
  Jenis truk yang digunakan: Arm Roll Truck (kapasitas 18 m^3)

[ACO] Vehicle 8: Pool Tanjungsari → Tambak Deres → TPA Benowo → Pool Tanjungsari
  Total distance: 39.73 km
  Total volume sampah: 5.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)

[ACO] Vehicle 9: Pool Tanjungsari → Demak (Kali Butuh) → Sawahan → Simpang Dukuh → Pasar Genteng → Makam Peneleh → Pringadi → Kedung Anyar → Penghela → Panghela → Dupak → TPA Benowo → Pool Tanjungsari
  Total distance: 32.28 km
  Total volume sampah: 32.0 m^3
  Jenis truk yang digunakan: Arm Roll Truck (kapasitas 18 m^3)

[ACO] Vehicle 10: Pool Tanjungsari → Pesapen → TPA Benowo → Pool Tanjungsari
  Total distance: 29.32 km
  Total volume sampah: 2.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)

[ACO] Vehicle 11: Pool Tanjungsari → Kaiser → Prada Kali Kendal → TPA Benowo → Pool Tanjungsari
  Total distance: 24.80 km
  Total volume sampah: 6.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)

TOTAL DISTANCE ALL VEHICLES [ACO]: 383.86 km

# VRP WITH TABU SEARCH ALGORITHM

In [24]:
class TabuSearch:
    def __init__(self, points, capacities, max_vehicle_capacity, tabu_tenure=10, max_iterations=100):
        self.points = points  # List of coordinate tuples
        self.capacities = capacities  # Volume capacity for each point
        self.max_capacity = max_vehicle_capacity
        self.tabu_tenure = tabu_tenure
        self.max_iterations = max_iterations
        self.tabu_list = []
        self.best_solution = None
        self.best_distance = float('inf')
        
    def calculate_distance(self, route_indices):
        """Calculate total distance for a route given point indices"""
        if not route_indices:
            return 0
        
        total_dist = 0
        # Pool to first point
        total_dist += haversine(pool, self.points[route_indices[0]])
        
        # Between consecutive points
        for i in range(len(route_indices) - 1):
            total_dist += haversine(self.points[route_indices[i]], self.points[route_indices[i + 1]])
        
        # Last point to TPA and back to pool
        total_dist += haversine(self.points[route_indices[-1]], tpa)
        total_dist += haversine(tpa, pool)
        
        return total_dist
    
    def is_feasible(self, route_indices):
        """Check if route satisfies capacity constraint"""
        total_capacity = sum(self.capacities[i] for i in route_indices)
        return total_capacity <= self.max_capacity
    
    def get_neighbors(self, current_solution):
        """Generate neighborhood solutions using 2-opt and swap operations"""
        neighbors = []
        n = len(current_solution)
        
        if n < 2:
            return neighbors
        
        # 2-opt neighborhood: reverse segments
        for i in range(n - 1):
            for j in range(i + 1, n):
                neighbor = current_solution[:]
                neighbor[i:j+1] = reversed(neighbor[i:j+1])
                if self.is_feasible(neighbor):
                    neighbors.append(neighbor)
        
        # Swap neighborhood: swap two elements
        for i in range(n):
            for j in range(i + 1, n):
                neighbor = current_solution[:]
                neighbor[i], neighbor[j] = neighbor[j], neighbor[i]
                if self.is_feasible(neighbor):
                    neighbors.append(neighbor)
        
        return neighbors
    
    def is_tabu(self, move):
        """Check if a move is in tabu list"""
        return move in self.tabu_list
    
    def add_to_tabu(self, move):
        """Add move to tabu list with tenure management"""
        self.tabu_list.append(move)
        if len(self.tabu_list) > self.tabu_tenure:
            self.tabu_list.pop(0)
    
    def solve(self):
        """Main Tabu Search algorithm"""
        n = len(self.points)
        if n == 0:
            return [], 0
        if n == 1:
            return [[0]], self.calculate_distance([0])
        
        # Initialize with a random feasible solution
        current_solution = list(range(n))
        random.shuffle(current_solution)
        
        # Ensure initial solution is feasible
        attempts = 0
        while not self.is_feasible(current_solution) and attempts < 100:
            random.shuffle(current_solution)
            attempts += 1
        
        if not self.is_feasible(current_solution):
            # If no feasible solution found, try greedy construction
            current_solution = self.greedy_construction()
        
        current_distance = self.calculate_distance(current_solution)
        self.best_solution = current_solution[:]
        self.best_distance = current_distance
        
        print(f"    Initial solution distance: {current_distance/1000:.2f} km")
        
        # Main Tabu Search loop
        for iteration in range(self.max_iterations):
            neighbors = self.get_neighbors(current_solution)
            
            if not neighbors:
                print(f"    No feasible neighbors found at iteration {iteration}")
                break
            
            best_neighbor = None
            best_neighbor_distance = float('inf')
            best_move = None
            
            for neighbor in neighbors:
                distance = self.calculate_distance(neighbor)
                move = self.get_move(current_solution, neighbor)
                
                # Accept if not tabu or if it's better than best known solution (aspiration criterion)
                if not self.is_tabu(move) or distance < self.best_distance:
                    if distance < best_neighbor_distance:
                        best_neighbor = neighbor
                        best_neighbor_distance = distance
                        best_move = move
            
            if best_neighbor is None:
                print(f"    All neighbors are tabu at iteration {iteration}")
                break
            
            # Update current solution
            current_solution = best_neighbor
            current_distance = best_neighbor_distance
            
            # Update best solution if improved
            if current_distance < self.best_distance:
                self.best_solution = current_solution[:]
                self.best_distance = current_distance
                print(f"    Improved solution at iteration {iteration}: {self.best_distance/1000:.2f} km")
            
            # Add move to tabu list
            if best_move:
                self.add_to_tabu(best_move)
            
            # Progress report every 50 iterations
            if (iteration + 1) % 50 == 0:
                print(f"    Iteration {iteration + 1}/{self.max_iterations}, current: {current_distance/1000:.2f} km, best: {self.best_distance/1000:.2f} km")
        
        # Return the best solution as a single route
        return [self.best_solution], self.best_distance
    
    def greedy_construction(self):
        """Construct a feasible solution greedily"""
        remaining = list(range(len(self.points)))
        solution = []
        current_capacity = 0
        
        while remaining:
            best_idx = None
            best_distance = float('inf')
            
            for idx in remaining:
                if current_capacity + self.capacities[idx] <= self.max_capacity:
                    # Calculate distance from current position
                    current_pos = pool if not solution else self.points[solution[-1]]
                    distance = haversine(current_pos, self.points[idx])
                    
                    if distance < best_distance:
                        best_distance = distance
                        best_idx = idx
            
            if best_idx is not None:
                solution.append(best_idx)
                current_capacity += self.capacities[best_idx]
                remaining.remove(best_idx)
            else:
                # If no feasible addition, break (this might leave some points unvisited)
                break
        
        return solution
    
    def get_move(self, solution1, solution2):
        """Identify the move that transforms solution1 to solution2"""
        # Simple representation: just return the first difference found
        for i in range(len(solution1)):
            if solution1[i] != solution2[i]:
                for j in range(i + 1, len(solution1)):
                    if solution1[j] == solution2[i]:
                        return (i, j)  # Swap operation
        return None

In [25]:
# Map baru untuk Tabu Search
m4 = folium.Map(location=pool, zoom_start=12)
folium.Marker(location=pool, popup='Pool Tanjungsari', icon=folium.Icon(color='red')).add_to(m4)
folium.Marker(location=tpa, popup='TPA Benowo', icon=folium.Icon(color='green')).add_to(m4)

# Implementasi Tabu Search untuk setiap cluster
print("=== TABU SEARCH RESULTS ===")
total_distance_tabu = 0

for vid in range(n_vehicles):
    cluster_pts = coords[kmeans.labels_ == vid]
    
    print(f"Processing Vehicle {vid+1}: {len(cluster_pts)} points in cluster")
    
    if len(cluster_pts) == 0:
        print(f"[TABU] Vehicle {vid+1}: No points assigned to this cluster - SKIPPED")
        continue

    pts_list = [tuple(pt) for pt in cluster_pts]
    capacities = [coord_to_capacity[pt] for pt in pts_list]
    total_volume = sum(capacities)

    # Pilih truk terkecil yang muat
    truk_terpilih = None
    for _, row in df_truk.iterrows():
        if total_volume <= row['Volume (m^3)']:
            truk_terpilih = row
            break
    if truk_terpilih is None:
        truk_terpilih = df_truk.iloc[-1]  # Gunakan terbesar jika semuanya tidak cukup

    print(f"  Vehicle {vid+1} - Total volume: {total_volume:.1f} m^3, Selected truck: {truk_terpilih['Jenis Kendaraan']} (capacity: {truk_terpilih['Volume (m^3)']} m^3)")

    # Jalankan Tabu Search
    if len(pts_list) > 1:
        print(f"  Running Tabu Search for Vehicle {vid+1}...")
        tabu_search = TabuSearch(
            points=pts_list,
            capacities=capacities,
            max_vehicle_capacity=truk_terpilih['Volume (m^3)'],
            tabu_tenure=min(20, len(pts_list) * 2),  # Adaptive tabu tenure
            max_iterations=min(200, len(pts_list) * 50)  # Adaptive iterations
        )
        
        best_routes, best_distance = tabu_search.solve()
        
        # Since we want only one route per vehicle, take the first (and should be only) route
        if best_routes and best_routes[0]:
            route = best_routes[0]
            route_coords = [pts_list[i] for i in route]
            full_route = [pool] + route_coords + [tpa, pool]
            
            # Visualize the route
            folium.PolyLine(
                locations=full_route,
                color=colors[vid % len(colors)],
                weight=3,
                opacity=0.8,
                popup=f'Vehicle {vid+1} (Tabu Search)'
            ).add_to(m4)
            
            total_distance_tabu += best_distance
            
            # Output hasil
            path_names = [coord_to_name.get(c, 'Unknown') for c in full_route]
            print(f"[TABU] Vehicle {vid+1}: " + " → ".join(path_names))
            print(f"  Total distance: {best_distance/1000:.2f} km")
            print(f"  Total volume sampah: {total_volume:.1f} m^3")
            print(f"  Jenis truk yang digunakan: {truk_terpilih['Jenis Kendaraan']} (kapasitas {truk_terpilih['Volume (m^3)']} m^3)\n")
        else:
            print(f"  No feasible route found for Vehicle {vid+1}")
    
    else:
        # Hanya satu titik, buat rute sederhana
        single_route = [pool] + pts_list + [tpa, pool]
        folium.PolyLine(
            locations=single_route,
            color=colors[vid % len(colors)],
            weight=3,
            opacity=0.8,
            popup=f'Vehicle {vid+1} (Single Point)'
        ).add_to(m4)
        
        route_distance = haversine(pool, pts_list[0]) + haversine(pts_list[0], tpa) + haversine(tpa, pool)
        total_distance_tabu += route_distance
        
        path_names = [coord_to_name.get(c, 'Unknown') for c in single_route]
        print(f"[TABU] Vehicle {vid+1}: " + " → ".join(path_names))
        print(f"  Total distance: {route_distance/1000:.2f} km")
        print(f"  Total volume sampah: {total_volume:.1f} m^3")
        print(f"  Jenis truk yang digunakan: {truk_terpilih['Jenis Kendaraan']} (kapasitas {truk_terpilih['Volume (m^3)']} m^3)\n")
     
print(f"TOTAL DISTANCE (TABU SEARCH): {total_distance_tabu/1000:.2f} km")

# Tampilkan map
m4

=== TABU SEARCH RESULTS ===
Processing Vehicle 1: 6 points in cluster
  Vehicle 1 - Total volume: 11.0 m^3, Selected truck: Truk 3.5 Ton (capacity: 12 m^3)
  Running Tabu Search for Vehicle 1...
    Initial solution distance: 36.62 km
    Improved solution at iteration 0: 34.31 km
    Improved solution at iteration 1: 32.91 km
    Improved solution at iteration 2: 32.77 km
    Iteration 50/200, current: 33.96 km, best: 32.77 km
    Iteration 100/200, current: 34.96 km, best: 32.77 km
    Iteration 150/200, current: 35.21 km, best: 32.77 km
    Iteration 200/200, current: 35.15 km, best: 32.77 km
[TABU] Vehicle 1: Pool Tanjungsari → Pasar Kembang → Pandegiling → Kedondong → Keputran Selatan → Dinoyo → Rumah Sakit Darmo / Ketampon → TPA Benowo → Pool Tanjungsari
  Total distance: 32.77 km
  Total volume sampah: 11.0 m^3
  Jenis truk yang digunakan: Truk 3.5 Ton (kapasitas 12 m^3)

Processing Vehicle 2: 2 points in cluster
  Vehicle 2 - Total volume: 4.0 m^3, Selected truck: Truk Kecil (capacity: 7 m^3)
  Running Tabu Search for Vehicle 2...
    Initial solution distance: 41.98 km
    All neighbors are tabu at iteration 1
[TABU] Vehicle 2: Pool Tanjungsari → Giyu → Gayungsari → TPA Benowo → Pool Tanjungsari
  Total distance: 41.98 km
  Total volume sampah: 4.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)

Processing Vehicle 3: 3 points in cluster
  Vehicle 3 - Total volume: 8.0 m^3, Selected truck: Truk 3.5 Ton (capacity: 12 m^3)
  Running Tabu Search for Vehicle 3...
    Initial solution distance: 20.97 km
    Improved solution at iteration 0: 19.83 km
    All neighbors are tabu at iteration 3
[TABU] Vehicle 3: Pool Tanjungsari → Alas Malang → Kendung → Babat Jerawat → TPA Benowo → Pool Tanjungsari
  Total distance: 19.83 km
  Total volume sampah: 8.0 m^3
  Jenis truk yang digunakan: Truk 3.5 Ton (kapasitas 12 m^3)

Processing Vehicle 4: 5 points in cluster
  Vehicle 4 - Total volume: 15.0 m^3, Selected truck: Arm Roll Truck (capacity: 18 m^3)
  Running Tabu Search for Vehicle 4...
    Initial solution distance: 38.68 km
    Improved solution at iteration 0: 36.26 km
    Improved solution at iteration 1: 36.18 km
    All neighbors are tabu at iteration 10
[TABU] Vehicle 4: Pool Tanjungsari → Kayun → Srikana → Gubeng → Pacar Keling → Legundi Anggrek → TPA Benowo → Pool Tanjungsari
  Total distance: 36.18 km
  Total volume sampah: 15.0 m^3
  Jenis truk yang digunakan: Arm Roll Truck (kapasitas 18 m^3)

Processing Vehicle 5: 3 points in cluster
  Vehicle 5 - Total volume: 7.0 m^3, Selected truck: Truk Kecil (capacity: 7 m^3)
  Running Tabu Search for Vehicle 5...
    Initial solution distance: 42.10 km
    Improved solution at iteration 0: 40.35 km
    All neighbors are tabu at iteration 3
[TABU] Vehicle 5: Pool Tanjungsari → Jagir → 3R Jambangan → Gayung Pring → TPA Benowo → Pool Tanjungsari
  Total distance: 40.35 km
  Total volume sampah: 7.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)

Processing Vehicle 6: 4 points in cluster
  Vehicle 6 - Total volume: 8.0 m^3, Selected truck: Truk 3.5 Ton (capacity: 12 m^3)
  Running Tabu Search for Vehicle 6...
    Initial solution distance: 52.94 km
    Improved solution at iteration 0: 50.54 km
    Improved solution at iteration 1: 50.25 km
    All neighbors are tabu at iteration 6
[TABU] Vehicle 6: Pool Tanjungsari → Gebang Putih → Keputih → Medokan Ayu → Semolowaru Bahari → TPA Benowo → Pool Tanjungsari
  Total distance: 50.25 km
  Total volume sampah: 8.0 m^3
  Jenis truk yang digunakan: Truk 3.5 Ton (kapasitas 12 m^3)

Processing Vehicle 7: 8 points in cluster
  Vehicle 7 - Total volume: 27.0 m^3, Selected truck: Arm Roll Truck (capacity: 18 m^3)
  Running Tabu Search for Vehicle 7...
    Initial solution distance: 34.52 km
    Improved solution at iteration 0: 34.24 km
    All neighbors are tabu at iteration 10
[TABU] Vehicle 7: Pool Tanjungsari → Sulung Kali → Pecindilan → Tambak Rejo → Simolawang → Pasar Kapasan → TPA Benowo → Pool Tanjungsari
  Total distance: 34.24 km
  Total volume sampah: 27.0 m^3
  Jenis truk yang digunakan: Arm Roll Truck (kapasitas 18 m^3)

Processing Vehicle 8: 1 points in cluster
  Vehicle 8 - Total volume: 5.0 m^3, Selected truck: Truk Kecil (capacity: 7 m^3)
[TABU] Vehicle 8: Pool Tanjungsari → Tambak Deres → TPA Benowo → Pool Tanjungsari
  Total distance: 39.73 km
  Total volume sampah: 5.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)

Processing Vehicle 9: 10 points in cluster
  Vehicle 9 - Total volume: 32.0 m^3, Selected truck: Arm Roll Truck (capacity: 18 m^3)
  Running Tabu Search for Vehicle 9...
    Initial solution distance: 28.45 km
    All neighbors are tabu at iteration 15
[TABU] Vehicle 9: Pool Tanjungsari → Demak (Kali Butuh) → Kedung Anyar → Pringadi → Penghela → Panghela → Dupak → TPA Benowo → Pool Tanjungsari
  Total distance: 28.45 km
  Total volume sampah: 32.0 m^3
  Jenis truk yang digunakan: Arm Roll Truck (kapasitas 18 m^3)

Processing Vehicle 10: 1 points in cluster
  Vehicle 10 - Total volume: 2.0 m^3, Selected truck: Truk Kecil (capacity: 7 m^3)
[TABU] Vehicle 10: Pool Tanjungsari → Pesapen → TPA Benowo → Pool Tanjungsari
  Total distance: 29.32 km
  Total volume sampah: 2.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)

Processing Vehicle 11: 2 points in cluster
  Vehicle 11 - Total volume: 6.0 m^3, Selected truck: Truk Kecil (capacity: 7 m^3)
  Running Tabu Search for Vehicle 11...
    Initial solution distance: 24.80 km
    All neighbors are tabu at iteration 1
[TABU] Vehicle 11: Pool Tanjungsari → Kaiser → Prada Kali Kendal → TPA Benowo → Pool Tanjungsari
  Total distance: 24.80 km
  Total volume sampah: 6.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)

TOTAL DISTANCE (TABU SEARCH): 377.90 km

# VRP WITH SIMULATED ANNEALING

In [19]:
#SA Function
def simulated_annealing(points, volumes, capacity, initial_temp=500, cooling_rate=0.98, stop_temp=10):
    from functools import lru_cache

    n = len(points)
    current = list(range(n))
    random.shuffle(current)

    def total_distance(route):
        dist = 0
        prev = pool
        for idx in route:
            dist += haversine(prev, points[idx])
            prev = points[idx]
        dist += haversine(prev, tpa) + haversine(tpa, pool)
        return dist

    def is_valid(route):
        load = 0
        for i in route:
            load += volumes[i]
            if load > capacity:
                return False
        return True

    # Cari solusi awal yang valid
    tries = 0
    while not is_valid(current):
        random.shuffle(current)
        tries += 1
        if tries > 1000:
            raise Exception("Gagal mendapatkan solusi awal yang valid")

    best = current[:]
    best_dist = total_distance(best)
    temp = initial_temp
    iter_count = 0

    while temp > stop_temp:
        iter_count += 1
        neighbor = current[:]
        i, j = random.sample(range(n), 2)
        neighbor[i], neighbor[j] = neighbor[j], neighbor[i]

        if not is_valid(neighbor):
            temp *= cooling_rate
            continue

        curr_dist = total_distance(current)
        neighbor_dist = total_distance(neighbor)
        delta = neighbor_dist - curr_dist

        if delta < 0 or math.exp(-delta / temp) > random.random():
            current = neighbor
            if neighbor_dist < best_dist:
                best = neighbor[:]
                best_dist = neighbor_dist

        temp *= cooling_rate

        if iter_count % 100 == 0:
            print(f"  Iterasi {iter_count}, suhu: {temp:.2f}, best: {best_dist/1000:.2f} km")

    return [points[i] for i in best]

In [20]:
# Map baru untuk Simulated Annealing
m5 = folium.Map(location=pool, zoom_start=12)
folium.Marker(location=pool, popup='Pool Tanjungsari', icon=folium.Icon(color='red')).add_to(m5)
folium.Marker(location=tpa, popup='TPA Benowo', icon=folium.Icon(color='green')).add_to(m5)

# Implementasi Simulated Annealing untuk setiap cluster
print("=== SIMULATED ANNEALING RESULTS ===")
total_distance_sa = 0

for vid in range(n_vehicles):
    cluster_pts = coords[kmeans.labels_ == vid]
    if len(cluster_pts) == 0:
        continue

    pts_list = [tuple(pt) for pt in cluster_pts]
    capacities = [coord_to_capacity[pt] for pt in pts_list]
    total_volume = sum(capacities)

    # Pilih truk terkecil yang muat
    truk_terpilih = None
    for _, row in df_truk.iterrows():
        if total_volume <= row['Volume (m^3)']:
            truk_terpilih = row
            break
    if truk_terpilih is None:
        truk_terpilih = df_truk.iloc[-1]  # Gunakan terbesar jika semuanya tidak cukup

    # Jalankan Simulated Annealing
    if len(pts_list) > 1:
        print(f"\n[SA] Processing Vehicle {vid+1} with {len(pts_list)} stops...")
        try:
            best_route = simulated_annealing(
                points=pts_list,
                volumes=capacities,
                capacity=truk_terpilih['Volume (m^3)'],
                initial_temp=1000,
                cooling_rate=0.95,
                stop_temp=1
            )
            
            # Hitung total jarak rute
            def calculate_total_distance(route_points):
                dist = haversine(pool, route_points[0])
                for i in range(len(route_points) - 1):
                    dist += haversine(route_points[i], route_points[i+1])
                dist += haversine(route_points[-1], tpa)
                dist += haversine(tpa, pool)
                return dist
            
            route_distance = calculate_total_distance(best_route)
            total_distance_sa += route_distance
            
            # Bangun rute lengkap untuk visualisasi
            full_route = [pool] + best_route + [tpa, pool]
            color = colors[vid % len(colors)]
            
            folium.PolyLine(
                locations=full_route,
                color=color,
                weight=3,
                opacity=0.8,
                popup=f'Vehicle {vid+1} (SA)'
            ).add_to(m5)
            
            # Output hasil
            path_names = [coord_to_name.get(c, 'Unknown') for c in full_route]
            print(f"[SA] Vehicle {vid+1}: " + " → ".join(path_names))
            print(f"  Total distance: {route_distance/1000:.2f} km")
            print(f"  Total volume sampah: {total_volume:.1f} m^3")
            print(f"  Jenis truk yang digunakan: {truk_terpilih['Jenis Kendaraan']} (kapasitas {truk_terpilih['Volume (m^3)']} m^3)\n")
            
        except Exception as e:
            print(f"  Error with Vehicle {vid+1}: {e}")
            # Fallback ke rute sederhana
            simple_route = [pool] + pts_list + [tpa, pool]
            folium.PolyLine(
                locations=simple_route,
                color=colors[vid % len(colors)],
                weight=2.5,
                opacity=0.8,
                popup=f'Vehicle {vid+1} (Fallback)'
            ).add_to(m5)
            
            route_distance = haversine(pool, pts_list[0])
            for i in range(len(pts_list) - 1):
                route_distance += haversine(pts_list[i], pts_list[i+1])
            route_distance += haversine(pts_list[-1], tpa) + haversine(tpa, pool)
            total_distance_sa += route_distance
            
            path_names = [coord_to_name.get(c, 'Unknown') for c in simple_route]
            print(f"[SA] Vehicle {vid+1} (Fallback): " + " → ".join(path_names))
            print(f"  Total distance: {route_distance/1000:.2f} km")
            print(f"  Total volume sampah: {total_volume:.1f} m^3")
            print(f"  Jenis truk yang digunakan: {truk_terpilih['Jenis Kendaraan']} (kapasitas {truk_terpilih['Volume (m^3)']} m^3)\n")
    
    else:
        # Hanya satu titik, buat rute sederhana
        single_route = [pool] + pts_list + [tpa, pool]
        folium.PolyLine(
            locations=single_route,
            color=colors[vid % len(colors)],
            weight=2.5,
            opacity=0.8,
            popup=f'Vehicle {vid+1}'
        ).add_to(m5)
        
        route_distance = haversine(pool, pts_list[0]) + haversine(pts_list[0], tpa) + haversine(tpa, pool)
        total_distance_sa += route_distance
        
        path_names = [coord_to_name.get(c, 'Unknown') for c in single_route]
        print(f"[SA] Vehicle {vid+1}: " + " → ".join(path_names))
        print(f"  Total distance: {route_distance/1000:.2f} km")
        print(f"  Total volume sampah: {total_volume:.1f} m^3")
        print(f"  Jenis truk yang digunakan: {truk_terpilih['Jenis Kendaraan']} (kapasitas {truk_terpilih['Volume (m^3)']} m^3)\n")

print(f"TOTAL DISTANCE (SIMULATED ANNEALING): {total_distance_sa/1000:.2f} km")

# Tampilkan map
m5

=== SIMULATED ANNEALING RESULTS ===

[SA] Processing Vehicle 1 with 6 stops...
  Iterasi 100, suhu: 5.92, best: 32.91 km
[SA] Vehicle 1: Pool Tanjungsari → Pasar Kembang → Kedondong → Keputran Selatan → Dinoyo → Rumah Sakit Darmo / Ketampon → Pandegiling → TPA Benowo → Pool Tanjungsari
  Total distance: 32.91 km
  Total volume sampah: 11.0 m^3
  Jenis truk yang digunakan: Truk 3.5 Ton (kapasitas 12 m^3)


[SA] Processing Vehicle 2 with 2 stops...
  Iterasi 100, suhu: 5.92, best: 41.98 km
[SA] Vehicle 2: Pool Tanjungsari → Giyu → Gayungsari → TPA Benowo → Pool Tanjungsari
  Total distance: 41.98 km
  Total volume sampah: 4.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)


[SA] Processing Vehicle 3 with 3 stops...
  Iterasi 100, suhu: 5.92, best: 19.83 km
[SA] Vehicle 3: Pool Tanjungsari → Alas Malang → Kendung → Babat Jerawat → TPA Benowo → Pool Tanjungsari
  Total distance: 19.83 km
  Total volume sampah: 8.0 m^3
  Jenis truk yang digunakan: Truk 3.5 Ton (kapasitas 12 m^3)


[SA] Processing Vehicle 4 with 5 stops...
  Iterasi 100, suhu: 5.92, best: 36.27 km
[SA] Vehicle 4: Pool Tanjungsari → Legundi Anggrek → Pacar Keling → Gubeng → Srikana → Kayun → TPA Benowo → Pool Tanjungsari
  Total distance: 36.27 km
  Total volume sampah: 15.0 m^3
  Jenis truk yang digunakan: Arm Roll Truck (kapasitas 18 m^3)


[SA] Processing Vehicle 5 with 3 stops...
  Iterasi 100, suhu: 5.92, best: 40.35 km
[SA] Vehicle 5: Pool Tanjungsari → Jagir → 3R Jambangan → Gayung Pring → TPA Benowo → Pool Tanjungsari
  Total distance: 40.35 km
  Total volume sampah: 7.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)


[SA] Processing Vehicle 6 with 4 stops...
  Iterasi 100, suhu: 5.92, best: 50.25 km
[SA] Vehicle 6: Pool Tanjungsari → Gebang Putih → Keputih → Medokan Ayu → Semolowaru Bahari → TPA Benowo → Pool Tanjungsari
  Total distance: 50.25 km
  Total volume sampah: 8.0 m^3
  Jenis truk yang digunakan: Truk 3.5 Ton (kapasitas 12 m^3)


[SA] Processing Vehicle 7 with 8 stops...
  Error with Vehicle 7: Gagal mendapatkan solusi awal yang valid
[SA] Vehicle 7 (Fallback): Pool Tanjungsari → Sulung Kali → Simolawang → Pasar Kapasan → Tambak Rejo → Pecindilan → Nyamplungan → Kertopaten → Wonokusumo Kidul → TPA Benowo → Pool Tanjungsari
  Total distance: 40.91 km
  Total volume sampah: 27.0 m^3
  Jenis truk yang digunakan: Arm Roll Truck (kapasitas 18 m^3)

[SA] Vehicle 8: Pool Tanjungsari → Tambak Deres → TPA Benowo → Pool Tanjungsari
  Total distance: 39.73 km
  Total volume sampah: 5.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)


[SA] Processing Vehicle 9 with 10 stops...
  Error with Vehicle 9: Gagal mendapatkan solusi awal yang valid
[SA] Vehicle 9 (Fallback): Pool Tanjungsari → Demak (Kali Butuh) → Pringadi → Penghela → Dupak → Simpang Dukuh → Pasar Genteng → Makam Peneleh → Kedung Anyar → Sawahan → Panghela → TPA Benowo → Pool Tanjungsari
  Total distance: 36.25 km
  Total volume sampah: 32.0 m^3
  Jenis truk yang digunakan: Arm Roll Truck (kapasitas 18 m^3)

[SA] Vehicle 10: Pool Tanjungsari → Pesapen → TPA Benowo → Pool Tanjungsari
  Total distance: 29.32 km
  Total volume sampah: 2.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)


[SA] Processing Vehicle 11 with 2 stops...
  Iterasi 100, suhu: 5.92, best: 24.80 km
[SA] Vehicle 11: Pool Tanjungsari → Kaiser → Prada Kali Kendal → TPA Benowo → Pool Tanjungsari
  Total distance: 24.80 km
  Total volume sampah: 6.0 m^3
  Jenis truk yang digunakan: Truk Kecil (kapasitas 7 m^3)

TOTAL DISTANCE (SIMULATED ANNEALING): 392.60 km

# Final Algorithm Comparison

In [21]:
# Bandingkan hasil semua algoritma
print("=== COMPREHENSIVE ALGORITHM COMPARISON ===")
print("\n1. Genetic Algorithm (GA):")
print("   - Menggunakan crossover dan mutasi untuk evolusi populasi")
print("   - Baik untuk eksplorasi ruang solusi yang luas")
print("   - Tidak mempertimbangkan kapasitas kendaraan secara eksplisit")

print("\n2. Ant Colony Optimization (ACO):")
print("   - Menggunakan pheromone trails untuk mencari jalur optimal")
print(f"   - Total distance: {total_distance_aco/1000:.2f} km")
print("   - Terinspirasi dari perilaku koloni semut")
print("   - Mempertimbangkan kapasitas kendaraan dalam pemilihan truk")

print("\n3. Tabu Search:")
print("   - Menggunakan memori tabu untuk menghindari local optima")
print("   - Melakukan pencarian lokal dengan pembatasan gerakan")
print(f"   - Total distance: {total_distance_tabu/1000:.2f} km")
print("   - Mempertimbangkan kapasitas kendaraan secara ketat")

print("\n4. Simulated Annealing (SA):")
print("   - Menggunakan probabilitas penerimaan solusi yang menurun")
print("   - Dapat menerima solusi yang lebih buruk untuk menghindari local optima")
print(f"   - Total distance: {total_distance_sa/1000:.2f} km")
print("   - Mempertimbangkan kapasitas kendaraan dengan validasi ketat")

print("\n=== SUMMARY ===")
print("Semua algoritma menggunakan:")
print("- K-Means clustering untuk pembagian wilayah (11 kendaraan)")
print("- Data kapasitas sampah dari new_data.csv")
print("- Data kapasitas truk dari kapasitas-truk.csv")
print("- Rute: Pool Tanjungsari → TPS/Depo → TPA Benowo → Pool Tanjungsari")

print("\nPerbandingan Total Jarak:")
print(f"- Ant Colony Optimization: {total_distance_aco/1000:.2f} km")
print(f"- Tabu Search: {total_distance_tabu/1000:.2f} km")
print(f"- Simulated Annealing: {total_distance_sa/1000:.2f} km")

# Tentukan algoritma terbaik
algo_results = {
    # "Genetic Algorithm": float('inf'),  # Belum dihitung dengan constraint kapasitas
    "Ant Colony Optimization": total_distance_aco,
    "Tabu Search": total_distance_tabu,
    "Simulated Annealing": total_distance_sa
}
# Temukan algoritma dengan total distance paling kecil
best_algo = min(algo_results, key=algo_results.get)
best_distance = algo_results[best_algo]
print(f"\nAlgoritma terbaik: {best_algo} dengan total jarak {best_distance/1000:.2f} km")

=== COMPREHENSIVE ALGORITHM COMPARISON ===

1. Genetic Algorithm (GA):
   - Menggunakan crossover dan mutasi untuk evolusi populasi
   - Baik untuk eksplorasi ruang solusi yang luas
   - Tidak mempertimbangkan kapasitas kendaraan secara eksplisit

2. Ant Colony Optimization (ACO):
   - Menggunakan pheromone trails untuk mencari jalur optimal
   - Total distance: 383.86 km
   - Terinspirasi dari perilaku koloni semut
   - Mempertimbangkan kapasitas kendaraan dalam pemilihan truk

3. Tabu Search:
   - Menggunakan memori tabu untuk menghindari local optima
   - Melakukan pencarian lokal dengan pembatasan gerakan
   - Total distance: 316.81 km
   - Mempertimbangkan kapasitas kendaraan secara ketat

4. Simulated Annealing (SA):
   - Menggunakan probabilitas penerimaan solusi yang menurun
   - Dapat menerima solusi yang lebih buruk untuk menghindari local optima
   - Total distance: 392.60 km
   - Mempertimbangkan kapasitas kendaraan dengan validasi ketat

=== SUMMARY ===
Semua algoritma menggunakan:
- K-Means clustering untuk pembagian wilayah (11 kendaraan)
- Data kapasitas sampah dari new_data.csv
- Data kapasitas truk dari kapasitas-truk.csv
- Rute: Pool Tanjungsari → TPS/Depo → TPA Benowo → Pool Tanjungsari

Perbandingan Total Jarak:
- Ant Colony Optimization: 383.86 km
- Tabu Search: 316.81 km
- Simulated Annealing: 392.60 km

Algoritma terbaik: Tabu Search dengan total jarak 316.81 km